### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getContextAttributes')

### ISSUE THREAD

**Issue by dalidaliW** [NativeScript/canvas#101]
### Issue Description

	this.canvas = args.object;
		const gl = this.canvas.getContext('webgl2', { antialias: false });
		// let drawingBufferWidth = gl.drawingBufferWidth
		// let drawingBufferHeight  =  gl.drawingBufferHeight
		// const { drawingBufferWidth: width, drawingBufferHeight: height } = gl;
		var engine: any
		var scene: any
		var sceneToRender: any
		var createDefaultEngine = function () {

			
			return new BABYLON.Engine(gl, true, { preserveDrawingBuffer: false, stencil: true, antialias: false });
		};

### Relevant log output (if applicable)

```shell
Refreshing application on device emulator-5554...
  JS: CONSOLE LOG: unloaded
  JS: CONSOLE LOG: Canvas<canvas>@main-page.xml:8:9; 9999
  System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method contextReady failed
  System.err: TypeError: Cannot read properties of null (reading 'getContextAttributes')
  System.err:
  System.err: StackTrace:
  System.err: getContextAttributes(file: app\webpack:\videoPlayer\node_modules\@nativescript\canvas\WebGL\WebGLRenderingContext\index.android.js:628:0)
  System.err:   at e(file: app\webpack:\videoPlayer\node_modules\babylonjs\babylon.js:16:367652)
  System.err:   at t(file: app\webpack:\videoPlayer\node_modules\babylonjs\babylon.js:16:112846)
  System.err:   at createDefaultEngine(file: app\webpack:\videoPlayer\app\canvas\canvas.ts:45:10)
  System.err:   at canvasLoaded(file: app\webpack:\videoPlayer\app\canvas\canvas.ts:50:11)
  System.err:   at _handleEvent(file: app\webpack:\videoPlayer\node_modules\@nativescript\core\data\observable\index.js:303:0)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Successfully synced application org.nativescript.videoPlayer on device emulator-5554.
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by triniwiz** [comment]
Can you share the packages used ?

**Comment by dalidaliW** [comment]
> Can you share the packages used ?

https://github.com/NativeScript/canvas/blob/cc723b4504a6878d8e25ec6b1fea22f5ca949f30/tools/demo/canvas-babylon/index.ts#L10

**Comment by dalidaliW** [comment]
> Can you share the packages used ?

Is there anything to pay attention to when using canvas-babylon

**Comment by dalidaliW** [comment]
> Can you share the packages used ?

`{
  "name": "videoPlayer",
  "main": "app/app.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@nativescript/canvas": "^1.1.0",
    "@nativescript/canvas-babylon": "^1.1.0",
    "@nativescript/canvas-media": "^1.1.0",
    "@nativescript/core": "~8.5.0",
    "@nativescript/canvas-polyfill": "^1.0.0",
    "@nativescript/theme": "~3.0.2",
    "babylonjs": "^4.1.0",
    "babylonjs-materials": "^4.1.0",
    "babylonjs-loaders": "^4.1.0"
  },
  "devDependencies": {
    "@nativescript/android": "8.5.1",
    "@nativescript/types": "~8.5.0",
    "@nativescript/webpack": "~5.0.14",
    "typescript": "~4.8.4"
  }
}
`

**Comment by triniwiz** [comment]
> > Can you share the packages used ?
> 
> Is there anything to pay attention to when using canvas-babylon

Not really but when using any external canvas lib I would recommend installing the `@nativescript/canvas-polyfill` then calling `require('@nativescript/canvas-polyfill')` as early as possible to let the polyfill work it's magic

**Comment by triniwiz** [comment]
Fixed in v2
