### ISSUE TITLE
Trying to create image with no canvas on screen

### ISSUE THREAD

**Issue by ericuldall** [NativeScript/canvas#102]
Currently trying the following but it always just returns a white pixel.
```
      const bg = await ImageSource.fromFile('~/assets/img/record-share-one.png');
      const base64Bg = bg.toBase64String("png");
      const canvas = new Canvas();
      canvas.setAttribute('width', 1238);
      canvas.setAttribute('height', 552);
      const ctx = canvas.getContext('2d');
      ctx.drawImage(base64Bg, 0, 0, 1238, 552);
      console.log(canvas.toDataURL());
```

Is this something that's possible?

**Comment by ericuldall** [comment]
Ended up doing a hack by setting canvas opacity to 0. Works for now!

**Comment by VanderSP** [comment]
Sorry to ask, but what you are needing to do exactly? Offscreen i guess it´s for working inside workers

**Comment by ericuldall** [comment]
I'm trying to generate an image for sharing only. It should not be rendered in the mobile app itself but it gets dynamically created then the sharing dialog is opened on the OS with the image in there.

**Comment by VanderSP** [comment]
you tried the snapshot command?

**Comment by ericuldall** [comment]
I used .toDataUrl
