### ISSUE TITLE
Dom don't work in iOS

### ISSUE THREAD

**Issue by vallemar** [NativeScript/canvas#117]
Android is being used directly in the Dom view, so it does not work on iOS
https://github.com/NativeScript/canvas/blob/master/packages/canvas/Dom/Dom.ts#L16

**Comment by vallemar** [comment]
@triniwiz I have been trying to solve it by replacing it with a stackLayout but then I have an error in `_addViewToNativeVisualTree` that I have not been able to solve 😭

**Comment by triniwiz** [comment]
You need UIView then addSubview.

**Comment by vallemar** [comment]
Working on iOS in beta.3!
