### ISSUE TITLE
TwoPointConicalGradient strange behavior

### ISSUE THREAD

**Issue by vallemar** [NativeScript/canvas#118]
When I do the same example as RN Skia I get this

<img width="476" alt="image" src="https://github.com/NativeScript/canvas/assets/15719383/08793eea-ea83-4e6d-a5ee-94a71b71ef7b">

I would expect to see this
https://shopify.github.io/react-native-skia/docs/shaders/gradients#example-2

My code
```html
 <Dom>
          <Rect x="0" y="0" width="256" height="256">
               <TwoPointConicalGradient :start="{ x: 0, y: 0 }" startR="128" :end="{ x: 256, y: 256 }" endR="16" :colors="['#bd34fe', '#65adf1']" />
          </Rect>
</Dom>
```

Same on ios y android

**Comment by triniwiz** [comment]
Look at the start point

**Comment by vallemar** [comment]
@triniwiz oh sorry, it works perfect!!!
