### ISSUE TITLE
Phaser-ce loader stuck with any type of asset

### ISSUE THREAD

**Issue by DavidTalevski** [NativeScript/canvas#14]
First of all, nice job on the plugins. I was trying to setup a phaser game running on nativescript but I've stumbled upon a problem. While I did get the canvas running well (I tested out the draw functions and they worked flawlessly) and the phaser game object, I can't seem to get the loader to work properly. I've setup all of the loading events to try and debug the situation but the loader seems to be getting stuck without any errors or logs. Here's my code:
```javascript
import TNSPhaser from "@nativescript/canvas-phaser-ce";

class State extends Phaser.State {
    preload() {
        console.log("Preload");
        this.game.load.onLoadStart.add(this.loadStart, this);
        this.game.load.onFileError.add(this.loadError, this);
        this.game.load.onFileComplete.add(this.fileComplete, this);
        this.game.load.onLoadComplete.add(this.loadComplete, this);
        this.game.load.onFileStart.add(this.fileStart, this);
        this.game.load.image('test', 'test.jpg');
    }

    fileStart(id) {
        console.log("fileStart", id);
    }

    loadError(err) {
        console.log("loadError");
        console.log(err);
    }

    loadStart() {
        console.log("loadStart");
    }

    fileComplete(result) {
        console.log("fileComplete", result);
    }

    loadComplete() {
        console.log("loadComplete");
    }

    create() {
        console.log("create");
        this.game.add.sprite(0, 0, 'test');
    }
}

export function canvasReady(args) {
    console.log('canvas ready');
    let canvas = args.object;
    let state = new State();
    TNSPhaser.Game({
        canvas,
        renderer: 1,
        state: state
    });
}
```

The output I'm getting is :
JS: Preload
JS: loadStart
JS: fileStart 0

So the events indicate that the loader actually started but it's not indicating whether the asset has failed to load or has finished loading. Under normal circumstances it should have either loaded the image or thrown an error saying the path is wrong or the file couldn't be found. I've tried giving it a random path string (this.game.load.image('test', 'sdggsdg');) hoping that it would throw an error indicating that the loader is working properly, but it got stuck again without any errors. Is this is a known problem or am I doing something wrong ?

This was tested on a real device: 
Model: Blackview A20 Pro.
Android version: 8.1.0

**Comment by triniwiz** [comment]
Thanks for trying I have an update coming this week which fixes this for sure

**Comment by DavidTalevski** [comment]
Thank you for your quick response, I also noticed another issue but I'm not sure whether to open it separately. When I set the renderer to Phaser.CANVAS ( 1 ) the sprites do not render at all and the screen is black, but when I set it to Phaser.WEBGL ( 2 ) or Phaser.AUTO which picks Phaser.WEBGL the sprites render on the canvas visibly ( with a green box of course because I can't load a texture ).

**Comment by triniwiz** [comment]
CANVAS would be usable again also the texture loading should be improved in the next release 😄 did some nice updates

**Comment by triniwiz** [comment]
Fixed : https://github.com/NativeScript/canvas/commit/d0cb7e3caf5925010f7a85b047dd082eaa54869a updated to the latest to enjoy
