### ISSUE TITLE
Performance!!!!!!

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/canvas#2]
- [x] Rewrite handling GL in rust 
- [x] use rust bindings in v8 *bye bye bridge

**Comment by DimitrisRK** [comment]
@triniwiz I did some tests with Canvas 2D in demo app, specifically with ChartJS sample.
I noticed that app hangs after multiple draw attempts in canvas.
My device runs Android 11. It feels like a memory leak occurs.

**Comment by triniwiz** [comment]
Thanks I'll do some more testing

**Comment by DimitrisRK** [comment]
> Thanks I'll do some more testing

It looks like it just requires some time, perhaps for garbage collection to take place and I stressed Canvas view a bit too much.
Animation made this issue more apparent if I updated chart data too fast.

**Comment by triniwiz** [comment]
@DimitrisRK If you can try using it with ios and LMK how that behaves

**Comment by VanderSP** [comment]
bye byeeeeeeeeeeeeeeeee bridge!

**Comment by triniwiz** [comment]
implemented in https://github.com/NativeScript/canvas/commit/b23b821a5f569faf12187be5eb71e3c5be8743d3
