### ISSUE TITLE
NSVue - Unknown custom element: <canvas>

### ISSUE THREAD

**Issue by sebj54** [NativeScript/canvas#22]
Hi!

I followed the documentation and it seems that docs are incomplete.

According to my personal experience with your other plugins, I have to do this in my `main.js` file:

```js
import Vue from 'nativescript-vue'
import CanvasPlugin from '@nativescript/canvas/vue'

Vue.use(CanvasPlugin)
```

The fact is that there is no `vue` folder with version 0.9.9 installed with npm (`ns plugin add @nativescript/canvas`). So I ended up doing:

```js
import Vue from 'nativescript-vue'

Vue.registerElement('Canvas', () => require('@nativescript/canvas').Canvas)
```

I wanted to make a PR to update the docs, but maybe you'll want to fix the missing `vue` folder before.

**Comment by triniwiz** [comment]
Thanks will do

**Comment by triniwiz** [comment]
Interesting because that directory exists so it seems to be a build issue

**Comment by sebj54** [comment]
Exactly! The `vue` folder is in repo but not in the npm package. It's weird because there are other similar folders like `react` or `svelte` in the npm package 🤔

**Comment by triniwiz** [comment]
fixed in https://github.com/NativeScript/canvas/commit/9f842dfe4b7bd3881d9c0a35797a27ca2b77533f
