### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by joshmossas** [NativeScript/canvas#25]
## Environment:
OS: Windows 10
Nativescript CLI: v8.0.1
Android Runtime: v8.0.0
Ios Runtime: v8.0.0

## Issue

I installed the following plugins in my project to give it a go `@nativescript/canvas`,
`@nativescript/canvas-polyfill`, `@nativescript/canvas-three`  however when I run `ns run` I get the following error.

```bash
Build file 'C:\Users\joshm\Documents\Modii\Projects\hiit-workout-app\hiitman\projects\hiitman-nativescript\platforms\android\app\build.gradle' line: 633
A problem occurred configuring project ':app'.
Could not GET 'https://jitpack.io/com/github/triniwiz/canvas/0.9.11/canvas-0.9.11.pom'. Received status code 401 from server: 
Unauthorized
```

For some reason there's an http request going to a private repo. (https://jitpack.io/com/github/triniwiz/canvas/0.9.11/canvas-0.9.11.pom) It's preventing my app from building.

I also tried removing `@nativescript/canvas-three` and got the same error

**Comment by triniwiz** [comment]
Can you try `@nativescript/canvas@latest` You should get .12 which fixes this

**Comment by joshmossas** [comment]
@latest gave me v0.9.13 but that seems to be working thanks! 

I noticed that this package expects xmldom to be installed but it's not listed as a peer dependency. I'll open another issue for it though.

**Comment by triniwiz** [comment]
`xmldom` is a dep for `@nativescript/canvas-polyfill`
