### ISSUE TITLE
@nativescript/canvas-pixi

### ISSUE THREAD

**Issue by sal1n** [NativeScript/canvas#29]
Hi

I've tried the simple usage example in:  https://github.com/NativeScript/canvas/tree/master/packages/canvas-pixi

I get this error:  _Error: com.tns.NativeScriptException: Failed to find module: "url", relative to: app/tns_modules/_ which doesn't really help me identity the issue.

I'm doing this in NS Vue (latest).  The Canvas element loads fine and I can draw to it on canvasReady.   I've tried adding:

`import '@nativescript/canvas-polyfill'`

early on in case that was the issue but didn't help.

I've just tried just rendering a rectangle with simplified code and get same error:

```
const canvas = args.object;
const app = new TNSPIXIApplication({
    canvas,
    backgroundColor: 0x1099bb,
});
var graphics = new PIXI.Graphics();
graphics.beginFill(0xFFFF00);
graphics.lineStyle(5, 0xFF0000);
graphics.drawRect(0, 0, 300, 200);
app.stage.addChild(graphics);
```

Any suggestions on other things I could try?  

Thanks.

**Comment by triniwiz** [comment]
To test can you import the polyfill in the `app.ts/app.js` thanks

**Comment by sal1n** [comment]
Yes, same error:  https://github.com/sal1n/test-pixi/blob/main/app/app.js 

To rule out interference from other code I've tried again with a brand new app, repo link above if that helps.  I initially get a _This initially gives a D8: Cannot fit requested classes in a single dex file (# methods: 86117 > 65536)_ error but adding multiDexEnabled = true to build.gradle seems to sort that issue but the _Failed to find module: "url", relative to: app/tns_modules/_ issue remains.

Could it be the pixi.js version perhaps?  https://github.com/sal1n/test-pixi/blob/main/package.json

**Comment by triniwiz** [comment]
Thanks for the demo

**Comment by sal1n** [comment]
I've tried with "pixi.js": "5.3.3" but same error.  Wonder if it's the NS version now.

**Comment by triniwiz** [comment]
Try adding the following to your webpack config it will be added to the base config in the next release 

```ts
	webpack.chainWebpack(config => {
		config.set('externalsPresets', {
			node: false
		  })
	  })
```

**Comment by sal1n** [comment]
Hi

Ah nice one.  That removes the original error but then I get:

`Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context`

I think this is from the actual libs:

```
    import * as PIXI from "pixi.js"
    import { TNSPIXIApplication } from "@nativescript/canvas-pixi"
```

because if I comment out that (plus the actual pixi code) it works.

**Comment by triniwiz** [comment]
Can you try switching the order an lmk

```
    import { TNSPIXIApplication } from "@nativescript/canvas-pixi"
    import * as PIXI from "pixi.js"
```

**Comment by sal1n** [comment]
Same error.

**Comment by triniwiz** [comment]
@sal1n can you try with the latest version

**Comment by sal1n** [comment]
Same error I'm afraid.

**Comment by triniwiz** [comment]
The lib(PIXI) is trying to run some compat tests but that is being started before the {N} activity has been created so in turn we have context to setup the canvas for them to run their tests a work around is to move the imports into the `canvasReady` .. iOS should not need to do something like this ...  test an lmk

```ts
 const { TNSPIXIApplication } = require("@nativescript/canvas-pixi");
const PIXI  = require("pixi.js");
```

**Comment by sal1n** [comment]
That works!  Yes I was testing on Android.  Thanks for you help.

**Comment by triniwiz** [comment]
I have some ideas on how to fix that
