### ISSUE TITLE
Bintray is being deprecated

### ISSUE THREAD

**Issue by MattCCC** [NativeScript/canvas#30]
Therefore cfg files like https://dl.bintray.com/triniwiz/maven/com/github/triniwiz/canvas/0.9.15/canvas-0.9.15.pom cannot be loaded in newest version of the plugin

**Comment by triniwiz** [comment]
Currently in the process of setting up a new [host](https://issues.sonatype.org/browse/OSSRH-67195)

**Comment by triniwiz** [comment]
Done:  https://github.com/NativeScript/canvas/commit/25ecb97fe1827cc3558cb3307824d1559b50c514
