### ISSUE TITLE
Android font issues

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [NativeScript/canvas#39]
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.0.2 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 8.0.7 and the latest available version is 8.0.8.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 8.0.0 version and is up to date.

First, setting more than one family in font spec makes canvas ignore the whole spec. So there's no way to specify fallback family.

Second, there doesn't seem to be a way to use custom fonts. Whether I'm specifying family name or file name, it always displays Roboto. If I specify "serif", that works, but being limited to 2 fonts is not exactly ideal.

Also, accepting Android native font instances would be a huge improvement, as it would allow to easily dynamically load fonts.
That, of course, would be a deviation from canvas spec,  but `drawImage()` already accepts android Bitmaps, so it's not that far-fetched.

**Comment by triniwiz** [comment]
It should be able to use the custom fonts so that not working seems to be an issue on my end , there are also some other hidden things :D e.g the 2d gl surface backed canvas can be switched to a bitmap so one can create views similar to how the android ui works 😄 same with ios

**Comment by triniwiz** [comment]
Fixed with https://github.com/NativeScript/canvas/commit/4d87d63452d27690e9ddf0f0baa5cbad84cd8644
