### ISSUE TITLE
Vulkan Support

### ISSUE THREAD

**Issue by triniwiz** [NativeScript/canvas#4]

**Comment by frank-unovica** [comment]
+1

**Comment by frank-unovica** [comment]
Actually, it should be a separate core module since vulkan is much more than rendering.
The actual renderer can then be written in ES, and or including a compute abstraction.
Then that renderer can be used as a canvas backend.

**Comment by triniwiz** [comment]
This was more for allowing it to be used in 2d , when this issue was created it was possible to use metal in 2D . Now it can also be used in WenGPU


Sent from Yahoo Mail for iPhone


On Wednesday, November 17, 2021, 7:07 AM, frank-unovica ***@***.***> wrote:




Actually, it should be a separate core module since vulkan is much more than rendering.
The actual renderer can then be written in ES, and or including a compute abstraction.
Then that renderer can be used as a canvas backend.

**Comment by triniwiz** [comment]
Added https://github.com/NativeScript/canvas/commit/9a5723f7f7b6aa555e8a3f020ffc8bfc5753ad50
