### ISSUE TITLE
Drawing canvas on canvas doesn't work

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [NativeScript/canvas#40]
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.0.2 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 8.0.7 and the latest available version is 8.0.8.
✖ Component @nativescript/ios is not installed.
✔ Component @nativescript/android has 8.0.0 version and is up to date.

If I create a second canvas with `createCustomView()`, draw something on them, and then try to draw them into the first canvas with `ctx.drawImage(innerCanvas, 0, 0)` nothing is drawn.
There are no errors, simply the image doesn't appear.

**Comment by HakobiDev** [comment]
Same issue.. in 2D canvas for Android doesn't work but in iOS it does.

**Comment by triniwiz** [comment]
Can you try updating to the latest `alpha` tag a lmk if that fixes it

**Comment by OzymandiasTheGreat** [comment]
No deal. Still, nothing is drawn with the latest alpha.
