### ISSUE TITLE
Tab navigation breaks canvas on Android

### ISSUE THREAD

**Issue by chris-praxis** [NativeScript/canvas#41]
[Home.vue.zip](https://github.com/NativeScript/canvas/files/6705234/Home.vue.zip)
[CanvasTest.vue.zip](https://github.com/NativeScript/canvas/files/6705235/CanvasTest.vue.zip)

In this simple test, Android graphics BufferQueue is lost after switching pages/tabs.  It's not a full working demo but should be very easy to repro with what I've provided.

1. After timeout, orange draws over blue as expected (both platforms).

2. Page is unloaded and reloaded via tab navigation (BottomNavigation & TabContentItem)...
iOS: Canvas appears the same, orange rectangle in blue.
Android: Canvas has reverted to all blue (background color), and when 'fillRect' is called again I get errors...

06-23 15:42:01.878 15438 15438 I JS      : 'draw canvas: Canvas<canvas> 960x1563'
06-23 15:42:01.884 15438 15752 E BufferQueueProducer: [SurfaceTexture-0-15438-0](id:3c4e00000000,api:1,p:15438,c:15438) dequeueBuffer: BufferQueue has been abandoned
06-23 15:42:01.884 15438 15752 E BufferQueueProducer: [SurfaceTexture-0-15438-0](id:3c4e00000000,api:1,p:15438,c:15438) dequeueBuffer: BufferQueue has been abandoned
06-23 15:42:01.884 15438 15752 E GLContext: Cannot swap buffers!

NS 6 + Vue
tns version 8.0.2
Dependencies:
```
┌──────────────────────────────┬────────────┐
│ Plugin                       │ Version    │
│ @nativescript/canvas         │ ^0.9.22-v6 │
│ @nativescript/email          │ ^2.0.4     │
│ crypto-js                    │ ^3.3.0     │
│ lodash.clonedeep             │ ^4.5.0     │
│ lodash.debounce              │ ^4.0.8     │
│ lodash.merge                 │ ^4.6.2     │
│ nativescript-in-app-purchase │ ^1.0.1     │
│ nativescript-plugin-firebase │ ^10.6.3    │
│ nativescript-shadowed-label  │ ^1.0.0     │
│ nativescript-theme-core      │ ~1.0.6     │
│ nativescript-vue             │ ~2.4.0     │
│ tns-core-modules             │ ^6.5.27    │
│ uglifyjs-webpack-plugin      │ ^2.2.0     │
└──────────────────────────────┴────────────┘
```
Dev Dependencies:
```
┌────────────────────────────────────┬─────────┐
│ Plugin                             │ Version │
│ @babel/core                        │ ~7.1.0  │
│ @babel/preset-env                  │ ~7.1.0  │
│ atob                               │ ^2.1.2  │
│ babel-loader                       │ ~8.0.0  │
│ nativescript-dev-webpack           │ ^1.5.1  │
│ nativescript-vue-template-compiler │ ~2.4.0  │
│ node-sass                          │ ^4.14.1 │
│ serialize-javascript               │ ^5.0.1  │
│ tns-android                        │ 6.5.3   │
│ tns-ios                            │ 6.5.3   │
│ typescript                         │ ^3.8.3  │
│ vue-loader                         │ ~15.4.0 │
└────────────────────────────────────┴─────────┘
```

**Comment by chris-praxis** [comment]
[CanvasTest.vue.zip](https://github.com/NativeScript/canvas/files/6711811/CanvasTest.vue.zip)
This version creates a new Canvas ever time tab page is entered/loaded instead of defining via XML, but it results in the same errors when drawing canvases after the first one.  Looks like a stale BufferQueue is still accessed, even though it's a new canvas.?

**Comment by triniwiz** [comment]
[CanvasTest.vue 2.zip](https://github.com/NativeScript/canvas/files/6712217/CanvasTest.vue.2.zip)
 I would go about it more like

**Comment by triniwiz** [comment]
Hey can you try the latest `alpha` tag an lmk

**Comment by darkyelox** [comment]
> Hey can you try the latest `alpha` tag an lmk

This is happening with alpha too, simply draw a rectangle in a canvas inside of a tab using the @nativescript-community/ui-material-bottom-navigation, navigate to the next tab and back to the first one and the canvas is empty.

I test using a (tap) event for redraw the canvas when "clicking", if I navigate to a tab and then go back to the first tab (the one with the canvas) and "click it" for call my draw function it throws `GLContext: Cannot swap buffers!`, if the first time I tap the component for redraw (without navigating to another tab) it draws and no error is thrown.

**Comment by triniwiz** [comment]
Please try again using {N} 8.1

**Comment by darkyelox** [comment]
@triniwiz tested using NS 8.1 and canvas 1.0.0-debug.0 and the same problem: the canvas disappears while a navigation to another view is being performed on Android, I'm  using Angular 12 with RootLayout as my wrapper for page-router-outlet btw, so the canvas becomes invisible when nsRouterLink is used, still needing the workaround that i have in previous comment.

**Comment by triniwiz** [comment]
You should stick with the alpha, debug is an actual debug version of the libs with the symbols included

**Comment by triniwiz** [comment]
Can you try with the latest , please reopen if the issue still persists
