### ISSUE TITLE
Empty textures are not empty (on iOS)

### ISSUE THREAD

**Issue by Mwni** [NativeScript/canvas#42]
When creating an empty texture using `gl.texImage2D()`, where the passed data is `null`, you get a texture that is prefilled with color (1, 1, 1, 0.5), while on browser you get (0, 0, 0, 0). Is this intended?

**Comment by triniwiz** [comment]
Is it the same on both platforms ?

**Comment by Mwni** [comment]
Forgot to specify, this is on iOS. For Android I cannot tell, because my emulator won't install. But I will report back as soon as I get that working.

**Comment by triniwiz** [comment]
Starting to feel it might just be an ios thing since [this](https://github.com/NativeScript/canvas/blob/master/packages/canvas/src-native/canvas-ios/CanvasNative/Source/TNSWebGLRenderingContext.swift#L1511-L1514) is how I handle it

**Comment by Mwni** [comment]
Right, I mean this is not a big issue. I could just call `gl.clear(0,0,0,0)` after creation, which is probably good practise anyways. I will close this now.
