### ISSUE TITLE
floating point textures are pixel slurry on iOS

### ISSUE THREAD

**Issue by Mwni** [NativeScript/canvas#45]
When trying to sample from a floating point texture (RGBA32F/FLOAT), you get random pixels. See attached screenshot below

<img width="208" src="https://user-images.githubusercontent.com/13929820/126671296-9ef0e1bb-8fbd-433d-9d01-246262c8322f.png">

The texture has been cleared with color (0, 0, 0, 0), so unfortunately, as shown above, this is not just a matter of floats being interpreted as ints. Sadly I cannot confirm that the texture is actually filled with (0, 0, 0, 0), since `gl.readPixels()` does not write anything.

Is there some maybe flag missing that tells the backend "this is a float texture"?

**Comment by triniwiz** [comment]
Thanks for trying this those numbers should be passed to gl as floats [{N}](https://github.com/NativeScript/canvas/blob/master/packages/canvas/WebGL/WebGLRenderingContext/index.ios.ts#L215) - > [ios](https://github.com/NativeScript/canvas/blob/master/packages/canvas/src-native/canvas-ios/CanvasNative/Source/TNSWebGLRenderingContext.swift#L335) as for `readPixels` I followed a web [impl](https://chromium.googlesource.com/chromium/blink/+/refs/heads/main/Source/modules/webgl/WebGLRenderingContextBase.cpp#3718) a bit so I feel [this](https://github.com/NativeScript/canvas/blob/master/packages/canvas/src-native/canvas-ios/CanvasNative/Source/TNSWebGLRenderingContext.swift#L1368) may be causing an issue with what is returned . Feel free to share the code you used to test

**Comment by Mwni** [comment]
I did pass floats and it seems the issue is not with the texture itself, but rather its sampling in a fragment shader (using `texture(tex, uv)`)
Are float textures expected to actually work on iOS? I will post my isolated code if they SHOULD work.

**Comment by Mwni** [comment]
Okay, on device the texture is just blank instead of messy, regardless what color value i write to it using `clear`.Works with `uint8` textures.

**Comment by Mwni** [comment]
I noticed the call to `getExtention('WEBGL_color_buffer_float')` returns some constants, notably `"RGBA32F_EXT": 34836`. Should this one maybe be used instead of `gl.RGBA32F`?

**Comment by triniwiz** [comment]
Can you try this again an lmk

**Comment by Mwni** [comment]
Yes, this is working perfectly now. Thank you!
