### ISSUE TITLE
Module not found: Error: Can't resolve 'xmldom-qsa' in .../node_modules/@nativescript/canvas-polyfill

### ISSUE THREAD

**Issue by elcreator** [NativeScript/canvas#56]
Module not found: Error: Can't resolve 'xmldom-qsa' in '.../node_modules/@nativescript/canvas-polyfill'
resolve 'xmldom-qsa' in '.../node_modules/@nativescript/canvas-polyfill'
  Parsed request is a module
  using description file: .../node_modules/@nativescript/canvas-polyfill/package.json (relative path: .)
    resolve as module
      looking for modules in .../node_modules
        single file module
          using description file: .../package.json (relative path: ./node_modules/xmldom-qsa)
            no extension

I installed xmldom-qsa via `npm i xmldom-qsa` and error was gone. I think it should be in the canvas-polyfill dependencies or peerDependencies

**Comment by triniwiz** [comment]
Is this using the @beta version of the polyfill?

**Comment by elcreator** [comment]
@nativescript/canvas-phaser@beta requires @nativescript/canvas-polyfill@1.0.0-v6
Additional installation of the beta fixed this, thank you.
