### ISSUE TITLE
Elements not rendering in Android TV

### ISSUE THREAD

**Issue by kwhohasamullet** [NativeScript/canvas#58]
I am trying to use the canvas + canvas-pixi on an app running on Android TV. When run on an android phone device (Pixel 5 running latest Android) it works as expected. When the same code is run on an Android TV Device (Google Chromecast with TV - Android TV OS 10) the canvas is drawn and the background colour set is shown but no elements are drawn to screen.

For sake of a simple test I have used the sample code provided by @triniwiz in the issue below and have the same results. Works fine on an Android Phone but not on Android TV. I have done some quick checking and cannot see anything that says Android TV should handle openGL ES any differently, I have also confirmed that my Android TV device is capable of OpenGL ES 3.1.

-------------------------------------- Testing App -----------------------
[testCanvasApp.zip](https://github.com/NativeScript/canvas/files/7148575/testCanvasApp.zip)
_Originally posted by @triniwiz in https://github.com/NativeScript/canvas/issues/52#issuecomment-917485920_

**Comment by triniwiz** [comment]
Thanks is an interesting case since I never tested on an Android TV Device , I think the only tv related device I tested on was a firestick but that was using threejs

**Comment by kwhohasamullet** [comment]
This is something I would like to see work but graphics /OpenGL is not something I have experience in.

Are there any logs or testing that I can do/testing tools Incan utilise that would be beneficial for either myself or you to start digging into this issue further?

**Comment by triniwiz** [comment]
[LogCat](https://developer.android.com/studio/command-line/logcat) is usually a helpful place to start

**Comment by triniwiz** [comment]
Can you try with the latest , please reopen if the issue still persists
