### ISSUE TITLE
apps.demo | Failed to build plugin @nativescript/canvas-media

### ISSUE THREAD

**Issue by 39ro** [NativeScript/canvas#63]
I was trying to run the demos app (apps.demo.android, apps.demo-angular.android) but it fail with the following error:

```
BUILD FAILED in 1s
Failed to build plugin @nativescript/canvas-media : 
Error: Command gradlew.bat failed with exit code 1
Done.

———————————————————————————————————————————————

>  NX   ERROR  Running target "demo-angular:android" failed
```

Is it a dependency conflict or something wrong in my environment?

**Comment by triniwiz** [comment]
Can you list the cmds you used ... thanks

**Comment by 39ro** [comment]
Pulled latest version
```
npm run start
> build-all
> apps.demo.android (&) apps.demo-angular.android 
```

**Comment by 39ro** [comment]
Same issue as above.
```
npm run setup

npm run start
> build-all

npm run start
> apps.demo.android (&) apps.demo-angular.android 


// dependencies

canvas-media: 0.12.0
canvas-three: 1.0.0-beta.1
core: 8.1.4
```

**Comment by triniwiz** [comment]
Ah seeing .bat so windows 🤔 ... after the build cmd cd into the apps/demo then run `ns run android --no-hmr`

**Comment by 39ro** [comment]
`ns run android --no-hmr` has the same behaviour of running apps.demo.android script and no extra errors are thrown.
I just  tried to download the project on a mac and I can experience the exact same issue.

```
BUILD FAILED in 4s
Failed to build plugin @nativescript/canvas-media : 
Error: Command ./gradlew failed with exit code 1
```

**Comment by 39ro** [comment]
@triniwiz thanks for jumping in help. I was able to run the demos on both devices just by removing the Android SDK build tools 31.0.0 looks like a corruption error was thrown (Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.).
https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted
