### ISSUE TITLE
nativescript-vue with canvas-three

### ISSUE THREAD

**Issue by aymux** [NativeScript/canvas#66]
Hi ^^
Is there any roadmap for the THREE plugin development ?
I'd like to use it in a nativescript-vue js project.

Thx !

**Comment by triniwiz** [comment]
What seems to be the issue with it ?

**Comment by aymux** [comment]
I've tried to use it with no luck.
can't import (where to import) or use @nativescript/canvas-three within my project.

tested : in app.js, in component.

The documentation in very unclear to me, concerning the (needed ?) use of polyfill. We need stronger documentation.

the NPM version of plugin does not export TNSTHREE... (does not export anything)
Comparing with the old repo ( https://github.com/triniwiz/nativescript-three ) the @nativescript/canvas-three seems, well, empty ?

**Comment by aymux** [comment]
Ok ! Thanks i've managed to spin the cube ;)
