### ISSUE TITLE
CanvasRenderingContext2D.clip() does not seem to clip path

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/canvas#83]
I have ported all my chart custom code from web to NS and it seems that clipping doesn't apply as expected.
The example contains a group of stripes that should be clipped according to chart bars. It's only tested on android for the time being.

Here is a screenshot from web, where clip is applied:
![Screenshot from 2022-08-05 13-36-20](https://user-images.githubusercontent.com/55595100/183060580-9d00237a-735b-4bb6-b63e-fbfd286a5425.png)

And here is the same code with NativeScript canvas:
![297401417_722067608875964_7081423225367334773_n](https://user-images.githubusercontent.com/55595100/183060835-60691c87-2d89-4b93-9e07-45264a033d95.jpg)

**Comment by triniwiz** [comment]
Yes been wanting to get to this, it's fixed in v2 so I'll try to backport it
