### ISSUE TITLE
Android canvas becomes blank after few updates

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/canvas#84]
It seems that android canvas becomes completely blank after multiple updates and it's random.
May occur after 2, 5 or 20 drawings or during next drawing to canvas.

**Comment by triniwiz** [comment]
Can you edit the Canvas source in node_module to `this._canvas = new org.nativescript.canvas.TNSCanvas(activity, true);` and lmk if that changes anything for u

**Comment by CatchABus** [comment]
> Can you edit the Canvas source in node_module to `this._canvas = new org.nativescript.canvas.TNSCanvas(activity, true);` and lmk if that changes anything for u

Yes, CPU mode seems to be stable.

**Comment by CatchABus** [comment]
I wonder if it's related to when pending invalidate flag is set
Maybe it's not set early enough? For example, plugin attempts to make native call first, then update canvas state to pending.

```kt
       private fun updateCanvas() {
		// synchronized (canvasView.lock) {
		canvas.invalidateState = TNSCanvas.InvalidateState.PENDING
		//}
	}

	fun clearRect(x: Float, y: Float, width: Float, height: Float) {
		printLog("clearRect")
		canvas.queueEvent(Runnable {
			nativeClearRect(canvas.nativeContext, x, y, width, height)
			updateCanvas()
		})
	}

	fun fillRect(x: Float, y: Float, width: Float, height: Float) {
		printLog("fillRect")
		canvas.queueEvent(Runnable {
			nativeFillRect(canvas.nativeContext, x, y, width, height)
			updateCanvas()
		})
	}

	fun strokeRect(x: Float, y: Float, width: Float, height: Float) {
		printLog("strokeRect")
		canvas.queueEvent(Runnable {
			nativeStrokeRect(canvas.nativeContext, x, y, width, height)
			updateCanvas()
		})
	}
```
