### ISSUE TITLE
(ios): fill rule 'evenodd' has no effect

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/canvas#88]
When I try to use `evenodd` fill rule with method `fill`, my shape is not drawn.
Example:
```js
ctx.fill('evenodd');
```

Plain `fill()` call is working in general, but there seems to be a problem with `evenodd`.

**Comment by triniwiz** [comment]
Both platforms?

**Comment by CatchABus** [comment]
> Both platforms?

Android has no such problem. I experienced this on iOS.

**Comment by CatchABus** [comment]
I noticed this one persists even in 1.1.0 now.

**Comment by triniwiz** [comment]
Fixed in v2 https://github.com/NativeScript/canvas/commit/090056b26b6f42aeeca214a2e65d91c3344d20ff
