### ISSUE TITLE
(ios): Small context does not render

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/canvas#89]
In iOS, there are cases when canvas 2D will not draw if content to draw is minimal.
For example, this will not get drawn:
```js
var ctx = canvas.getContext('2d');

ctx.font = "40px 'Helvetica'";
ctx.fillText ("Hello World", 10, 60);
```

However, it gets drawn if I set `useCpu` to `true` in node_modules.

I suspect the default rendering mode expects a certain number of calls in order to draw, because charts get drawn in both modes. Chart.js is a good example because it performs lots of drawings on canvas.

**Comment by CatchABus** [comment]
@triniwiz It seems that chart won't get drawn too.
I discovered that putting my code inside a timeout helps canvas draw.

This will never draw:
```js
var ctx = canvas.getContext('2d');

ctx.font = "40px 'Helvetica'";
ctx.fillText ("Hello World", 10, 60);
```

This will draw:
```js
setTimeout(() => {
    var ctx = canvas.getContext('2d');

    ctx.font = "40px 'Helvetica'";
    ctx.fillText ("Hello World", 10, 60);
  }, 0);
```

Does that give any hints?

**Comment by triniwiz** [comment]
You mentioned small context, what is the size of the view ?

**Comment by triniwiz** [comment]
This should not be an issue in v2
