### ISSUE TITLE
(android): canvas content gets drawn out of bounds

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/canvas#90]
In android OS, there are times canvas drawn content starts outside of bounds.

This is how it normally gets drawn:

![image (2)](https://user-images.githubusercontent.com/55595100/190127735-fb989847-b0f5-49e0-9ef6-717db8f8ae9c.jpg)

This is the random case of starting drawing from out of bounds:

![image (1)](https://user-images.githubusercontent.com/55595100/190127881-3d2212b0-b0c4-4dd9-9a1b-6b2ad40bfb02.jpg)

**Comment by VanderSP** [comment]
Interesting the space between is larger

**Comment by CatchABus** [comment]
> Interesting the space between is larger

Yeah, it's because drawing has an earlier starting X point outside bounds for a reason.
Chart will calculate bar distance based on view available width.

**Comment by triniwiz** [comment]
Fixed in v2
