### ISSUE TITLE
canvas-babylon, no interaction possible and no file loading possible

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/canvas#91]
Hello together,
I am currently playing with the canvas-babylon plugin and I observed two major bugs.

@triniwiz: We have spoken about some of the topics below yesterday. However, I thought I add an issue here and provide you with a demo project to show the issues. Hope this is of some help.

First: There seems to be no interaction possible with the canvas. Tap und Touch events seem to have no effect on the canvas. Seems like this works with the three.js camera, but not with the babylon packages. I tried in Babylonjs with different cameras. For all cameras interaction is completely ignored

BABYLON.ArcRotateCamera
BABYLON.UniversalCamera

Second: I tried to load some geometry using babylonjs-loaders. Unfortunately also without success:

A minimum example can be downloaded from here:

https://github.com/cjohn001/babylon

Third: Feature request. It would be great if you could add version 5 of Babylon.js with the next update. There are packages with typings available at:

https://www.npmjs.com/package/@babylonjs/core

Thanks for the great plugin! I hope we can get the blockers out soon. Time is right to get an opengl-based scene graph into Nativescript :)

**Comment by triniwiz** [comment]
Touch handling has ben updated to behave similar to the web. If the touch doesn't respond it maybe due to it using mouse events.
