### ISSUE TITLE
[bug] Canvas content gets reset if app draws with delay

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/canvas#93]
It seems that if I draw something on canvas using a timeout, the previous drawing will be erased.
Seems to occur on android and ios (devices only)

Samples to test:

This works
```js

export function onContextReady(args) {
  var canvas = args.object;
  var ctx = canvas.getContext("2d");
  ctx.rect(50, 20, 200, 120);
  ctx.stroke();
  ctx.fillStyle = "red";
  ctx.fillRect(0, 0, 150, 100);
}
```
![Screenshot from 2022-11-17 12-38-49](https://user-images.githubusercontent.com/55595100/202424884-640cfd83-cfa6-4f18-8ee9-679b9e4dabd5.png)

This is with timeout. It will erase first shape and draw red rectangle alone
```js
export function onContextReady(args) {
  var canvas = args.object;
  var ctx = canvas.getContext("2d");
  ctx.rect(50, 20, 200, 120);
  ctx.stroke();
  ctx.fillStyle = "red";
  setTimeout(() => ctx.fillRect(0, 0, 150, 100), 2000);
}
```
![Screenshot from 2022-11-17 12-39-05](https://user-images.githubusercontent.com/55595100/202424965-ca83bff0-a140-4fcb-b293-08f01c4b92c5.png)

**Comment by triniwiz** [comment]
Fixed in https://github.com/NativeScript/canvas/commit/9a5723f7f7b6aa555e8a3f020ffc8bfc5753ad50
